export const Categories = {
  makeup: 'Makeup',
  nails: 'Nails',
  hair: 'Hair',
  eyebrows: 'Eyebrows',
  bodyCare: 'Body Care',
  lashes: 'Lashes',
};

export const Services = {
  makeup: {
    dayMakeup: 'Day Makeup',
    nightMakeup: 'Night Makeup',
    expressMakeup: 'Express Makeup',
    bridalMakeup: 'Bridal Makeup',
  },
  lashes: {
    eyelashExtensionsApplication1D: 'Eyelash extensions application 1D',
    eyelashExtensionsApplication2D: 'Eyelash extensions application 2D',
    eyelashExtensionsApplication3D: 'Eyelash extensions application 3D',
    eyelashExtensionsApplicationHollywood6D:
      'Eyelash extensions application Hollywood 6D',
    eyelashMaintenance: 'Eyelash Maintenance',
    eyelashFilling: 'Eyelash Filling',
    eyelashRemoval: 'Eyelash Removal',
    tintingEyelashes: 'Tinting Eyelashes',
    lashLamination: 'Lash Lamination',
  },
  eyebrows: {
    eyebrowShaping: 'Eyebrow Shaping',
    browsLamination: 'Brows Lamination',
    browsTinting: 'Brows Tinting',
    hennaEyebrowsTinting: 'Henna Eyebrows Tinting',
    micropigmentation: 'Micropigmentation',
    microblading: 'Microblading',
  },
  nails: {
    classicManicure: 'Classic Manicure',
    semiPermanentManicure: 'Semi-Permanent Manicure',
    gelOnNaturalNail: 'Gel on Natural Nail',
    technicalNailsConstructionOrTips: 'Technical Nails (Construction or Tips)',
    technicalNailsMaintenance: 'Technical Nails Maintenance',
    brokenNailReplacement: 'Broken Nail Replacement',
    nailPainting: 'Nail Painting',
    removingNails: 'Removing Nails',
    classicPedicure: 'Classic Pedicure',
    semiPermanentPedicure: 'Semi-Permanent Pedicure',
    gelPedicure: 'Gel Pedicure',
    manicurePedicurePackage: 'Manicure Pedicure Package',
  },
  bodyCare: {
    facialTreatments: 'Facial Treatments',
    waxing: 'Waxing',
    sugarWaxing: 'Sugar Waxing',
    permanentHairRemovalLaser: 'Permanent Hair Removal-Laser',
    permanentHairRemovalIPL: 'Permanent Hair Removal-IPL',
    electrolysis: 'Electrolysis',
    bodyRemodelingLPG: 'Body Remodeling-LPG',
    bodyRemodelingVelaShape: 'Body Remodeling-Vela Shape',
    antiCelluliteTreatment: 'Anti-Cellulite Treatment',
    pressotherapy: 'Pressotherapy',
    mesotherapy: 'Mesotherapy',
    coldAndHotPacks: 'Cold and Hot Packs',
    criolipolisis: 'Criolipolisis',
    bodyRadioFrequency: 'Body Radio Frequency',
    cavitation: 'Cavitation',
    lymphaticDrainage: 'Lymphatic Drainage',
    electrostimulation: 'Electrostimulation',
    massage: 'Massage',
  },
  hair: {
    haircut: 'Haircut',
    hairstyle: 'Hairstyle',
    hairColouring: 'Hair Colouring',
    hairWash: 'Hair Wash',
    treatments: 'Treatments',
    hairMassage: 'Hair Massage',
  },
};
